### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x14fc38830>

### ISSUE THREAD

**Issue by asisadh** [imepay/imepaySDK_iOS#2]
When I open the IME view the following error shows up. Not sure how to fix this.

Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x14fc38830>

**Comment by scubax07** [comment]
@asisadh did you fix this issue?

**Comment by asisadh** [comment]
Nope.

**Comment by scubax07** [comment]
i think its the problem with their sdk. might be gone if they present the vc setting animation false.

**Comment by asisadh** [comment]
I also thought it was the SDK issue, so created an issue here, but could not get the support from them.

**Comment by akash-stha** [comment]
> I also thought it was the SDK issue, so created an issue here, but could not get the support from them.

Did you solve this issue, sir?

**Comment by imashishbogati** [comment]
> > I also thought it was the SDK issue, so created an issue here, but could not get the support from them.
> 
> Did you solve this issue, sir?

Use initialized globals 
`import UIKit
import IMEPay

class ViewController: UIViewController {

    let manager = IMPPaymentManager(environment: Test)
    
    let button : UIButton = {
        let btn = UIButton()
        btn.setTitle("Pay", for: .normal)
        btn.setTitleColor(.white, for: .normal)
        btn.backgroundColor = .systemBlue
        btn.translatesAutoresizingMaskIntoConstraints = false
        btn.addTarget(self, action: #selector(touchPay), for: .touchUpInside)
        return btn
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        view.addSubview(button)
        NSLayoutConstraint.activate([
            self.button.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            self.button.trailingAnchor.constraint(equalTo: view.trailingAnchor,constant: -15),
            self.button.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 15),
            self.button.heightAnchor.constraint(equalToConstant: 50)
        ])
    }
    
    
    @objc func touchPay() {
        // For Test: Test For Live : Live
        self.manager?.pay(withUsername: "aquaworld", password: "ime@123", merchantCode: "AQUAWORLD", merchantName: "Aqua World Pvt. Ltd", merchantUrl: "www.aquaworld.com.np", amount: "20", referenceId: "9843935114", module: "AQUAWORLD", success: { (transactionInfo) in
            transactionInfo?.responseCode
        }, failure: { (transactionInfo, errorMessage) in
            print(errorMessage)
            print(transactionInfo?.responseCode)
        })
        
    }
    
}`

**Comment by imashishbogati** [comment]
> > I also thought it was the SDK issue, so created an issue here, but could not get the support from them.
> 
> Did you solve this issue, sir?
` let manager = IMPPaymentManager(environment: Test)
    
    let button : UIButton = {
        let btn = UIButton()
        btn.setTitle("Pay", for: .normal)
        btn.setTitleColor(.white, for: .normal)
        btn.backgroundColor = .systemBlue
        btn.translatesAutoresizingMaskIntoConstraints = false
        btn.addTarget(self, action: #selector(touchPay), for: .touchUpInside)
        return btn
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        view.addSubview(button)
        NSLayoutConstraint.activate([
            self.button.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            self.button.trailingAnchor.constraint(equalTo: view.trailingAnchor,constant: -15),
            self.button.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 15),
            self.button.heightAnchor.constraint(equalToConstant: 50)
        ])
    }
    
    

    // For Test: Test For Live : Live
    @objc func touchPay() {
        // For Test: Test For Live : Live
        self.manager?.pay(withUsername: "username" , password: "password", merchantCode: "merchantCode", merchantName: "merchantName",    merchantUrl: "merchantUrl", amount: "amount", referenceId: "referenceId", module: "module", success: { (transactionInfo) in
            transactionInfo?.responseCode
        }, failure: { (transactionInfo, errorMessage) in
            print(errorMessage)
            print(transactionInfo?.responseCode)
        })
        
    }`

**Comment by imashishbogati** [comment]
> > I also thought it was the SDK issue, so created an issue here, but could not get the support from them.
> 
> Did you solve this issue, sir?


`class ViewController: UIViewController {
    let manager = IMPPaymentManager(environment: Test)
    let button : UIButton = {
        let btn = UIButton()
        btn.setTitle("Pay", for: .normal)
        btn.setTitleColor(.white, for: .normal)
        btn.backgroundColor = .systemBlue
        btn.translatesAutoresizingMaskIntoConstraints = false
        btn.addTarget(self, action: #selector(touchPay), for: .touchUpInside)
        return btn
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        view.addSubview(button)
        NSLayoutConstraint.activate([
            self.button.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            self.button.trailingAnchor.constraint(equalTo: view.trailingAnchor,constant: -15),
            self.button.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 15),
            self.button.heightAnchor.constraint(equalToConstant: 50)
        ])
    }

    // For Test: Test For Live : Live
    @objc func touchPay() {
        // For Test: Test For Live : Live
        self.manager?.pay(withUsername: "username" , password: "password", merchantCode: "merchantCode", merchantName: "merchantName",    merchantUrl: "merchantUrl", amount: "amount", referenceId: "referenceId", module: "module", success: { (transactionInfo) in
            transactionInfo?.responseCode
        }, failure: { (transactionInfo, errorMessage) in
            print(errorMessage)
            print(transactionInfo?.responseCode)
        })
    }
}`

**Comment by imashishbogati** [comment]
> > I also thought it was the SDK issue, so created an issue here, but could not get the support from them.
> 
> Did you solve this issue, sir?

`class ViewController: UIViewController {

    let manager = IMPPaymentManager(environment: Test)
    
    let button : UIButton = {
        let btn = UIButton()
        btn.setTitle("Pay", for: .normal)
        btn.setTitleColor(.white, for: .normal)
        btn.backgroundColor = .systemBlue
        btn.translatesAutoresizingMaskIntoConstraints = false
        btn.addTarget(self, action: #selector(touchPay), for: .touchUpInside)
        return btn
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        view.addSubview(button)
        NSLayoutConstraint.activate([
            self.button.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            self.button.trailingAnchor.constraint(equalTo: view.trailingAnchor,constant: -15),
            self.button.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 15),
            self.button.heightAnchor.constraint(equalToConstant: 50)
        ])
    }
    
    

    // For Test: Test For Live : Live
    @objc func touchPay() {
        // For Test: Test For Live : Live
        self.manager?.pay(withUsername: "username" , password: "password", merchantCode: "merchantCode", merchantName: "merchantName",    merchantUrl: "merchantUrl", amount: "amount", referenceId: "referenceId", module: "module", success: { (transactionInfo) in
            transactionInfo?.responseCode
        }, failure: { (transactionInfo, errorMessage) in
            print(errorMessage)
            print(transactionInfo?.responseCode)
        })
        
    }
        
    
}`

**Comment by akash-stha** [comment]
> > > I also thought it was the SDK issue, so created an issue here, but could not get the support from them.
> > 
> > 
> > Did you solve this issue, sir?
> 
> `class ViewController: UIViewController {
> 
> ```
> let manager = IMPPaymentManager(environment: Test)
> 
> let button : UIButton = {
>     let btn = UIButton()
>     btn.setTitle("Pay", for: .normal)
>     btn.setTitleColor(.white, for: .normal)
>     btn.backgroundColor = .systemBlue
>     btn.translatesAutoresizingMaskIntoConstraints = false
>     btn.addTarget(self, action: #selector(touchPay), for: .touchUpInside)
>     return btn
> }()
> 
> override func viewDidLoad() {
>     super.viewDidLoad()
>     // Do any additional setup after loading the view.
>     view.addSubview(button)
>     NSLayoutConstraint.activate([
>         self.button.centerYAnchor.constraint(equalTo: view.centerYAnchor),
>         self.button.trailingAnchor.constraint(equalTo: view.trailingAnchor,constant: -15),
>         self.button.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 15),
>         self.button.heightAnchor.constraint(equalToConstant: 50)
>     ])
> }
> 
> 
> 
> // For Test: Test For Live : Live
> @objc func touchPay() {
>     // For Test: Test For Live : Live
>     self.manager?.pay(withUsername: "username" , password: "password", merchantCode: "merchantCode", merchantName: "merchantName",    merchantUrl: "merchantUrl", amount: "amount", referenceId: "referenceId", module: "module", success: { (transactionInfo) in
>         transactionInfo?.responseCode
>     }, failure: { (transactionInfo, errorMessage) in
>         print(errorMessage)
>         print(transactionInfo?.responseCode)
>     })
>     
> }
> ```
> 
> }`

Thanks Bro. It works.
